<h2>Section title</h2>
<div class="table-responsive">
    <table class="table table-striped table-sm">
        <thead>
            <tr>
                <th></th>
                <th>
                <select class="form-control">
                    <option selected>Статус</option>
                      <option>Бла</option>
                      <option>2</option>
                      <option>3</option>
                </select>
                </th>
                <th><input type="text" class="form-control" id="inputPassword2" placeholder="Фильтр1"></th>
                <th><input type="text" class="form-control" id="inputPassword2" placeholder="Фильтр1"></th>
                <th><input id="timepicker" width="100" /></th>
                <th><input id="timepicker1" width="100"/></th>
                <th>
                <select class="form-control">
                    <option selected>Рубежи</option>
                      <option>Бла</option>
                      <option>2</option>
                      <option>3</option>
                </select>
                </th>
                <th>
                <select class="form-control">
                    <option selected>Ответственные</option>
                      <option>Бла</option>
                      <option>2</option>
                      <option>3</option>
                </select>
                </th>
                <th>
                    <button type="button" class="btn btn-light">Очистить</button>
                </th>
            </tr>
        </thead>
        <thead>
            <tr>
                <th>#</th>
                <th>Header</th>
                <th>Header</th>
                <th>Header</th>
                <th>Header</th>
                <th>Header</th>
                <th>Header</th>
                <th>Header</th>
                <th>Header</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>1,001</td>
                <td>Lorem</td>
                <td>ipsum</td>
                <td>dolor</td>
                <td>sit</td>
                <td>dolor</td>
                <td>dolor</td>
                <td>sit</td>
                <td>dolor</td>
            </tr>
            <tr>
                <td>1,002</td>
                <td>amet</td>
                <td>consectetur</td>
                <td>adipiscing</td>
                <td>elit</td>
                <td>adipiscing</td>
                <td>dolor</td>
                <td>sit</td>
                <td>dolor</td>
            </tr>
            <tr>
                <td>1,003</td>
                <td>Integer</td>
                <td>nec</td>
                <td>odio</td>
                <td>Praesent</td>
                <td>odio</td>
                <td>dolor</td>
                <td>sit</td>
                <td>dolor</td>
            </tr>
            <tr>
                <td>1,003</td>
                <td>libero</td>
                <td>Sed</td>
                <td>cursus</td>
                <td>ante</td>
                <td>cursus</td>
                <td>dolor</td>
                <td>sit</td>
                <td>dolor</td>
            </tr>
            <tr>
                <td>1,004</td>
                <td>dapibus</td>
                <td>diam</td>
                <td>Sed</td>
                <td>nisi</td>
                <td>Sed</td>
                <td>dolor</td>
                <td>sit</td>
                <td>dolor</td>
            </tr>
            <tr>
                <td>1,005</td>
                <td>Nulla</td>
                <td>quis</td>
                <td>sem</td>
                <td>at</td>
                <td>sem</td>
                <td>dolor</td>
                <td>sit</td>
                <td>dolor</td>
            </tr>
            <tr>
                <td>1,006</td>
                <td>nibh</td>
                <td>elementum</td>
                <td>imperdiet</td>
                <td>Duis</td>
                <td>imperdiet</td>
                <td>dolor</td>
                <td>sit</td>
                <td>dolor</td>
            </tr>
            <tr>
                <td>1,007</td>
                <td>sagittis</td>
                <td>ipsum</td>
                <td>Praesent</td>
                <td>mauris</td>
                <td>Praesent</td>
                <td>dolor</td>
                <td>sit</td>
                <td>dolor</td>
            </tr>
            <tr>
                <td>1,008</td>
                <td>Fusce</td>
                <td>nec</td>
                <td>tellus</td>
                <td>sed</td>
                <td>tellus</td>
                <td>dolor</td>
                <td>sit</td>
                <td>dolor</td>
            </tr>
            <tr>
                <td>1,009</td>
                <td>augue</td>
                <td>semper</td>
                <td>porta</td>
                <td>Mauris</td>
                <td>porta</td>
                <td>dolor</td>
                <td>sit</td>
                <td>dolor</td>
            </tr>
            <tr>
                <td>1,010</td>
                <td>massa</td>
                <td>Vestibulum</td>
                <td>lacinia</td>
                <td>arcu</td>
                <td>lacinia</td>
                <td>dolor</td>
                <td>sit</td>
                <td>dolor</td>
            </tr>
            <tr>
                <td>1,011</td>
                <td>eget</td>
                <td>nulla</td>
                <td>Class</td>
                <td>aptent</td>
                <td>Class</td>
                <td>dolor</td>
                <td>sit</td>
                <td>dolor</td>
            </tr>
            <tr>
                <td>1,012</td>
                <td>taciti</td>
                <td>sociosqu</td>
                <td>ad</td>
                <td>litora</td>
                <td>ad</td>
                <td>dolor</td>
                <td>sit</td>
                <td>dolor</td>
            </tr>
            <tr>
                <td>1,013</td>
                <td>torquent</td>
                <td>per</td>
                <td>conubia</td>
                <td>nostra</td>
                <td>conubia</td>
                <td>dolor</td>
                <td>sit</td>
                <td>dolor</td>
            </tr>
            <tr>
                <td>1,014</td>
                <td>per</td>
                <td>inceptos</td>
                <td>himenaeos</td>
                <td>Curabitur</td>
                <td>himenaeos</td>
                <td>dolor</td>
                <td>sit</td>
                <td>dolor</td>
            </tr>
            <tr>
                <td>1,015</td>
                <td>sodales</td>
                <td>ligula</td>
                <td>in</td>
                <td>libero</td>
                <td>in</td>
                <td>dolor</td>
                <td>sit</td>
                <td>dolor</td>
            </tr>
        </tbody>
    </table>
</div>